import type { Metadata } from "next";
import "./globals.css";
import Provider from "./providers";
import Wrapper from "./wrapper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-50 font-sans bg-zinc-950 min-w-[375px] text-white">
        <Provider>
          <Wrapper>{children}</Wrapper>
        </Provider>
      </body>
    </html>
  );
}
